export function injectProxyScript(html, originalURL) {

    if (!html) {
        return html;
    }


    const encodedBase =
        Buffer
            .from(originalURL)
            .toString("base64")
            .replace(/\+/g, "-")
            .replace(/\//g, "_")
            .replace(/=/g, "");


    const script = `
<script>
(function () {

    "use strict";


    /*
     * ============================================================
     * PROXY RUNTIME
     * ============================================================
     *
     * The page is displayed from the proxy origin, while its
     * resources belong to the original upstream origin.
     *
     * Every HTTP(S) request generated by page JavaScript must
     * therefore be converted into:
     *
     *     /proxy?url=<encoded upstream URL>
     *
     * before the browser sends it.
     */


    const ORIGINAL_PAGE_URL =
        ${JSON.stringify(originalURL)};


    const PROXY_ORIGIN =
        window.location.origin;


    const ORIGINAL_PAGE_BASE =
        new URL(
            ORIGINAL_PAGE_URL
        );


    console.log(
        "PROXY INJECT ACTIVE:",
        ORIGINAL_PAGE_URL
    );



    /*
     * ============================================================
     * URL ENCODING
     * ============================================================
     */

    function encodeProxyURL(url) {

        try {

            const bytes =
                new TextEncoder().encode(url);

            let binary = "";

            for (
                let i = 0;
                i < bytes.length;
                i++
            ) {

                binary += String.fromCharCode(
                    bytes[i]
                );

            }

            return btoa(binary)
                .replace(/\\+/g, "-")
                .replace(/\\//g, "_")
                .replace(/=/g, "");

        }
        catch (error) {

            console.error(
                "PROXY ENCODE ERROR:",
                error
            );

            return null;

        }

    }



    /*
     * ============================================================
     * RESOLVE UPSTREAM URL
     * ============================================================
     */

    function resolveURL(value) {

        if (
            value === null ||
            value === undefined
        ) {

            return null;

        }


        const stringValue =
            String(value).trim();


        if (!stringValue) {

            return null;

        }


        /*
         * Leave non-network URLs alone.
         */

        if (
            stringValue.startsWith(
                "data:"
            ) ||
            stringValue.startsWith(
                "blob:"
            ) ||
            stringValue.startsWith(
                "javascript:"
            ) ||
            stringValue.startsWith(
                "mailto:"
            ) ||
            stringValue.startsWith(
                "#"
            )
        ) {

            return null;

        }


        try {

            /*
             * If the URL is already an upstream absolute URL,
             * preserve it.
             */

            if (
                /^https?:\\/\\//i.test(
                    stringValue
                )
            ) {

                return new URL(
                    stringValue
                ).href;

            }


            /*
             * Protocol-relative URL.
             */

            if (
                stringValue.startsWith(
                    "//"
                )
            ) {

                return new URL(
                    ORIGINAL_PAGE_BASE.protocol +
                    stringValue
                ).href;

            }


            /*
             * Absolute path such as:
             *
             * /ajax/bz
             *
             * MUST resolve against Instagram, not the proxy.
             */

            return new URL(
                stringValue,
                ORIGINAL_PAGE_BASE
            ).href;

        }
        catch (error) {

            console.error(
                "PROXY RESOLVE ERROR:",
                stringValue,
                error
            );

            return null;

        }

    }



    /*
     * ============================================================
     * BUILD LOCAL PROXY URL
     * ============================================================
     */

    function proxyURL(value) {

        /*
         * If this is already a proxy URL, don't proxy it again.
         */

        if (
            typeof value === "string" &&
            (
                value.startsWith(
                    "/proxy?url="
                ) ||
                value.startsWith(
                    PROXY_ORIGIN +
                    "/proxy?url="
                )
            )
        ) {

            return value;

        }


        const resolved =
            resolveURL(value);


        if (!resolved) {

            return value;

        }


        const encoded =
            encodeProxyURL(
                resolved
            );


        if (!encoded) {

            return value;

        }


        const proxied =
            PROXY_ORIGIN +
            "/proxy?url=" +
            encoded;


        console.log(
            "PROXY URL:",
            resolved,
            "=>",
            proxied
        );


        return proxied;

    }



    /*
     * ============================================================
     * FETCH HOOK
     * ============================================================
     */

    const originalFetch =
        window.fetch;


    window.fetch =
        function (
            input,
            init
        ) {

            try {

                let originalInput =
                    input;


                let requestURL;


                if (
                    typeof input ===
                    "string"
                ) {

                    requestURL =
                        input;

                }
                else if (
                    input &&
                    typeof input.url ===
                    "string"
                ) {

                    requestURL =
                        input.url;

                }


                const resolved =
                    resolveURL(
                        requestURL
                    );


                if (
                    resolved &&
                    /^https?:/i.test(
                        resolved
                    )
                ) {

                    const proxied =
                        proxyURL(
                            resolved
                        );


                    console.log(
                        "FETCH INTERCEPT:",
                        requestURL,
                        "=>",
                        resolved,
                        "=>",
                        proxied
                    );


                    /*
                     * A Request object needs special handling.
                     *
                     * Replacing it with a plain URL while preserving
                     * the original init object is unreliable for some
                     * browser APIs.
                     */

                    if (
                        input instanceof Request
                    ) {

                        const request =
                            new Request(
                                proxied,
                                input
                            );


                        return originalFetch.call(
                            this,
                            request,
                            init
                        );

                    }


                    input =
                        proxied;

                }

            }
            catch (error) {

                console.error(
                    "FETCH PROXY ERROR:",
                    error
                );

            }


            return originalFetch.call(
                this,
                input,
                init
            );

        };



    /*
     * ============================================================
     * XHR HOOK
     * ============================================================
     */

    const originalOpen =
        XMLHttpRequest.prototype.open;


    XMLHttpRequest.prototype.open =
        function (
            method,
            url,
            async,
            user,
            password
        ) {

            try {

                const resolved =
                    resolveURL(
                        url
                    );


                if (
                    resolved &&
                    /^https?:/i.test(
                        resolved
                    )
                ) {

                    const proxied =
                        proxyURL(
                            resolved
                        );


                    console.log(
                        "XHR INTERCEPT:",
                        method,
                        url,
                        "=>",
                        resolved,
                        "=>",
                        proxied
                    );


                    url =
                        proxied;

                }

            }
            catch (error) {

                console.error(
                    "XHR PROXY ERROR:",
                    error
                );

            }


            return originalOpen.call(
                this,
                method,
                url,
                async,
                user,
                password
            );

        };



    /*
     * ============================================================
     * WEBSOCKET VISIBILITY
     * ============================================================
     *
     * Do not attempt to proxy WebSockets yet.
     * Just log them so we can identify them separately.
     */

    const OriginalWebSocket =
        window.WebSocket;


    window.WebSocket =
        function (
            url,
            protocols
        ) {

            console.log(
                "WEBSOCKET REQUEST:",
                url
            );


            if (
                arguments.length > 1
            ) {

                return new OriginalWebSocket(
                    url,
                    protocols
                );

            }


            return new OriginalWebSocket(
                url
            );

        };


    window.WebSocket.prototype =
        OriginalWebSocket.prototype;



    console.log(
        "PROXY HOOKS READY:",
        ORIGINAL_PAGE_URL
    );


})();
</script>
`;


    /*
     * Inject immediately after <head> when possible.
     */

    if (
        /<head\\b[^>]*>/i.test(html)
    ) {

        return html.replace(
            /(<head\\b[^>]*>)/i,
            "$1" + script
        );

    }


    /*
     * Otherwise inject before the first script.
     */

    if (
        /<script\\b/i.test(html)
    ) {

        return html.replace(
            /(<script\\b)/i,
            script + "$1"
        );

    }


    /*
     * Last fallback.
     */

    return (
        script +
        html
    );

}